### ISSUE TITLE
(v1.1.2) strings_en.arb is generated for non dart/flutter projects

### ISSUE THREAD

**Issue by remcoanker** [long1eu/flutter_i18n#106]
After updating the plugin to V1.1.2, the plugin creates strings_en.arb for all Android Studio projects, even a new blank android project without dart or flutter. The file gets instantly regenerated after deleting.

**Comment by noordawod** [comment]
Thanks for the heads up! I'll check this asap and submit a new version.

**Comment by noordawod** [comment]
This is now fixed in #107 and submitted to JetBrains plugins repo. Hopefully it'll appear by tomorrow and you can upgrade.

**Comment by augustdong** [comment]
Still exists on version v.1.1.4-191, when open android projects on Android Studio, this plugin creates strings_en.arb on /android/res/values/ @noordawod

**Comment by noordawod** [comment]
Something in your environment is different than mine then because it doesn't happen here. I tested with many Android projects... There's a strict check in the Kotlin code for a Flutter-only project.

Can you check if a Flutter or Dart module is listed inside `.idea/modules.xml` file?

**Comment by pparadox11** [comment]
Hi, i am facing the same issue, any suggestion?

**Comment by beilly** [comment]
@noordawod ,when open Flutter project's android module, it creates strings_en.arb on /android/res/values/。I think it's not issues, but I can't build my Flutter project in Android platform. And can i close auto generate by another menu?
